FROM nginx:latest

RUN apt update && apt install -y openssl
# Optional: remove default.conf if you need to customize it
#RUN rm /etc/nginx/conf.d/default.conf

COPY generate_cert.sh /generate_cert.sh
RUN chmod +x /generate_cert.sh  && /generate_cert.sh
#RUN ./generate_cert.sh


# Copy your custom configuration and files
COPY nginx.conf /etc/nginx/nginx.conf
COPY html/ /usr/share/nginx/html
COPY ssl/ /etc/nginx/ssl


EXPOSE 8080
EXPOSE 4343

