version: '3.8'
services:

  certs:
    build: ./nginx
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    entrypoint: ["bash", "/generate_cert.sh"]
    networks:
      - mynetwork

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: userpassword123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  wordpress:
    build: ./wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - mynetwork

  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - "8080:8080"
      - "4343:4343"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - certs
      - wordpress
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
